# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’10.0’
use_frameworks!

target 'JYYTPointAcc' do
pod 'Alamofire', '~> 4.4.0’
pod 'AFNetworking'
pod 'SwiftyJSON'
pod 'YYModel'
end

target 'JYYTPointAccTests' do
end
